# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NotchFilter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(997, 656)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ch1 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch1.sizePolicy().hasHeightForWidth())
        self.ch1.setSizePolicy(sizePolicy)
        self.ch1.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ch1.setFont(font)
        self.ch1.setCheckable(True)
        self.ch1.setChecked(False)
        self.ch1.setObjectName("ch1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ch1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.ch1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.com_label_1 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.com_label_1.sizePolicy().hasHeightForWidth())
        self.com_label_1.setSizePolicy(sizePolicy)
        self.com_label_1.setObjectName("com_label_1")
        self.gridLayout.addWidget(self.com_label_1, 0, 0, 1, 1)
        self.set_label_1 = QtWidgets.QLabel(self.frame)
        self.set_label_1.setObjectName("set_label_1")
        self.gridLayout.addWidget(self.set_label_1, 2, 0, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_1.sizePolicy().hasHeightForWidth())
        self.comboBox_1.setSizePolicy(sizePolicy)
        self.comboBox_1.setEditable(True)
        self.comboBox_1.setObjectName("comboBox_1")
        self.gridLayout.addWidget(self.comboBox_1, 0, 1, 1, 1)
        self.open_button_1 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_button_1.sizePolicy().hasHeightForWidth())
        self.open_button_1.setSizePolicy(sizePolicy)
        self.open_button_1.setObjectName("open_button_1")
        self.gridLayout.addWidget(self.open_button_1, 0, 2, 1, 1)
        self.wave_label_1 = QtWidgets.QLabel(self.frame)
        self.wave_label_1.setMinimumSize(QtCore.QSize(0, 0))
        self.wave_label_1.setObjectName("wave_label_1")
        self.gridLayout.addWidget(self.wave_label_1, 3, 0, 1, 1)
        self.wave_lineEdit_1 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wave_lineEdit_1.sizePolicy().hasHeightForWidth())
        self.wave_lineEdit_1.setSizePolicy(sizePolicy)
        self.wave_lineEdit_1.setObjectName("wave_lineEdit_1")
        self.gridLayout.addWidget(self.wave_lineEdit_1, 3, 1, 1, 1)
        self.read_btn_1 = QtWidgets.QPushButton(self.frame)
        self.read_btn_1.setObjectName("read_btn_1")
        self.gridLayout.addWidget(self.read_btn_1, 3, 2, 1, 1)
        self.set_lineEdit_1 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_lineEdit_1.sizePolicy().hasHeightForWidth())
        self.set_lineEdit_1.setSizePolicy(sizePolicy)
        self.set_lineEdit_1.setText("")
        self.set_lineEdit_1.setObjectName("set_lineEdit_1")
        self.gridLayout.addWidget(self.set_lineEdit_1, 2, 1, 1, 2)
        self.verticalLayout.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(self.ch1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 1, 1, 1)
        self.inc_1 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inc_1.sizePolicy().hasHeightForWidth())
        self.inc_1.setSizePolicy(sizePolicy)
        self.inc_1.setObjectName("inc_1")
        self.gridLayout_2.addWidget(self.inc_1, 2, 3, 1, 1)
        self.dec_1 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dec_1.sizePolicy().hasHeightForWidth())
        self.dec_1.setSizePolicy(sizePolicy)
        self.dec_1.setObjectName("dec_1")
        self.gridLayout_2.addWidget(self.dec_1, 2, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 6, 1, 1)
        self.step_cbx_1 = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_cbx_1.sizePolicy().hasHeightForWidth())
        self.step_cbx_1.setSizePolicy(sizePolicy)
        self.step_cbx_1.setMinimumSize(QtCore.QSize(0, 0))
        self.step_cbx_1.setObjectName("step_cbx_1")
        self.gridLayout_2.addWidget(self.step_cbx_1, 1, 3, 1, 2)
        self.verticalLayout.addWidget(self.frame_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem3)
        self.frame_3 = QtWidgets.QFrame(self.ch1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.info_label_1 = QtWidgets.QLabel(self.frame_3)
        self.info_label_1.setObjectName("info_label_1")
        self.gridLayout_3.addWidget(self.info_label_1, 0, 0, 1, 1)
        self.plainTextEdit_1 = QtWidgets.QPlainTextEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.plainTextEdit_1.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_1.setSizePolicy(sizePolicy)
        self.plainTextEdit_1.setObjectName("plainTextEdit_1")
        self.gridLayout_3.addWidget(self.plainTextEdit_1, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.ch1)
        self.ch2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch2.sizePolicy().hasHeightForWidth())
        self.ch2.setSizePolicy(sizePolicy)
        self.ch2.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ch2.setFont(font)
        self.ch2.setCheckable(True)
        self.ch2.setChecked(False)
        self.ch2.setObjectName("ch2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ch2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.ch2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_7.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.wave_label_2 = QtWidgets.QLabel(self.frame_4)
        self.wave_label_2.setObjectName("wave_label_2")
        self.gridLayout_7.addWidget(self.wave_label_2, 2, 0, 1, 1)
        self.com_label_2 = QtWidgets.QLabel(self.frame_4)
        self.com_label_2.setObjectName("com_label_2")
        self.gridLayout_7.addWidget(self.com_label_2, 0, 0, 1, 1)
        self.open_button_2 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_button_2.sizePolicy().hasHeightForWidth())
        self.open_button_2.setSizePolicy(sizePolicy)
        self.open_button_2.setObjectName("open_button_2")
        self.gridLayout_7.addWidget(self.open_button_2, 0, 2, 1, 1)
        self.set_label_2 = QtWidgets.QLabel(self.frame_4)
        self.set_label_2.setObjectName("set_label_2")
        self.gridLayout_7.addWidget(self.set_label_2, 1, 0, 1, 1)
        self.set_lineEdit_2 = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_lineEdit_2.sizePolicy().hasHeightForWidth())
        self.set_lineEdit_2.setSizePolicy(sizePolicy)
        self.set_lineEdit_2.setText("")
        self.set_lineEdit_2.setObjectName("set_lineEdit_2")
        self.gridLayout_7.addWidget(self.set_lineEdit_2, 1, 1, 1, 2)
        self.wave_lineEdit_2 = QtWidgets.QLineEdit(self.frame_4)
        self.wave_lineEdit_2.setObjectName("wave_lineEdit_2")
        self.gridLayout_7.addWidget(self.wave_lineEdit_2, 2, 1, 1, 1)
        self.read_btn_2 = QtWidgets.QPushButton(self.frame_4)
        self.read_btn_2.setObjectName("read_btn_2")
        self.gridLayout_7.addWidget(self.read_btn_2, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem4)
        self.frame_5 = QtWidgets.QFrame(self.ch2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 8, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 1, 3, 1, 1)
        self.dec_2 = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dec_2.sizePolicy().hasHeightForWidth())
        self.dec_2.setSizePolicy(sizePolicy)
        self.dec_2.setObjectName("dec_2")
        self.gridLayout_5.addWidget(self.dec_2, 1, 5, 1, 1)
        self.inc_2 = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inc_2.sizePolicy().hasHeightForWidth())
        self.inc_2.setSizePolicy(sizePolicy)
        self.inc_2.setObjectName("inc_2")
        self.gridLayout_5.addWidget(self.inc_2, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 3, 1, 1)
        self.step_cbx_2 = QtWidgets.QComboBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_cbx_2.sizePolicy().hasHeightForWidth())
        self.step_cbx_2.setSizePolicy(sizePolicy)
        self.step_cbx_2.setMinimumSize(QtCore.QSize(0, 0))
        self.step_cbx_2.setObjectName("step_cbx_2")
        self.gridLayout_5.addWidget(self.step_cbx_2, 0, 4, 1, 2)
        self.verticalLayout_2.addWidget(self.frame_5)
        spacerItem7 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem7)
        self.frame_6 = QtWidgets.QFrame(self.ch2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.info_label_2 = QtWidgets.QLabel(self.frame_6)
        self.info_label_2.setObjectName("info_label_2")
        self.gridLayout_6.addWidget(self.info_label_2, 0, 0, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.plainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_2.setSizePolicy(sizePolicy)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout_6.addWidget(self.plainTextEdit_2, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.ch2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ch1.setTitle(_translate("Form", "CH1"))
        self.com_label_1.setText(_translate("Form", "COM Ports:"))
        self.set_label_1.setText(_translate("Form", "Set (nm):"))
        self.open_button_1.setText(_translate("Form", "Open"))
        self.wave_label_1.setText(_translate("Form", "Read (nm):"))
        self.read_btn_1.setText(_translate("Form", "Read"))
        self.label_2.setText(_translate("Form", "Wavelength (nm): "))
        self.inc_1.setText(_translate("Form", "Increase"))
        self.dec_1.setText(_translate("Form", "Decrease"))
        self.label.setText(_translate("Form", "Step (nm):"))
        self.info_label_1.setText(_translate("Form", "Setup Info:"))
        self.ch2.setTitle(_translate("Form", "CH2"))
        self.wave_label_2.setText(_translate("Form", "Read (nm):"))
        self.com_label_2.setText(_translate("Form", "COM Ports:"))
        self.open_button_2.setText(_translate("Form", "Open"))
        self.set_label_2.setText(_translate("Form", "Set (nm):"))
        self.read_btn_2.setText(_translate("Form", "Read"))
        self.label_3.setText(_translate("Form", "Wavelength (nm): "))
        self.dec_2.setText(_translate("Form", "Decrease"))
        self.inc_2.setText(_translate("Form", "Increase"))
        self.label_4.setText(_translate("Form", "Step (nm):"))
        self.info_label_2.setText(_translate("Form", "Setup Info:"))

